apiVersion: v1
kind: Service
metadata: {name: ble-sensors-mqtt}
spec:
  type: ClusterIP
  selector: {app.kubernetes.io/name: ble-sensors-mqtt}
  ports:
    - {name: frontend, port: 8080, targetPort: frontend, protocol: TCP}
    - {name: prometheus, port: 9105, targetPort: prometheus, protocol: TCP}
    - {name: snmp, port: 1161, targetPort: snmp, protocol: UDP}
